### ISSUE TITLE
Daily snapshots at nighttime

### ISSUE THREAD

**Issue by WojciechKarpiel** [FairwindsOps/gemini#25]
Hi!
My use case is: I want to do daily backups of my database, and I want snapshot to be performed at nighttime, when the traffic is minimal (say, between 23:00 and 1:00 UTC)

From what I see, the snapshot is scheduled when I create the SnapshotGroupResource. Is there a gaurantee that snapshot taking time will not diverge (I mean, will hourly snapshots be: 0:00, 1:01, 2:00, 2:59, 4:00 and not 0:00, 1:01, 2:04, 3:06, 4:09)?

Possible solutions (just random ideas):
* Allow Cron-like schedule specification (would add a lot of flexibility and be consistent with how Kubernetes CronJob is configured)

**Comment by rbren** [comment]
Cron schedules are a great idea!
