### ISSUE TITLE
Backup snapshot volume data to an external store

### ISSUE THREAD

**Issue by onedr0p** [FairwindsOps/gemini#26]
It would be great if this tool could also back up the data in the snapshot to s3, minio, or nfs. Restic is a great tool for this and would love to see the integration here. This would cover most disaster/recovery if your cluster was ever nuked or completely fubar.

Thanks.

**Comment by rbren** [comment]
Unfortunately something like this is out of scope for Gemini at this time. We want to avoid creating one-off integrations with storage providers, and instead rely on [the CSI](https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/) to handle the backups themselves.

That said, if the cluster is nuked, your EBS snapshots (assuming you're on AWS) should still be in tact, though it might take some work to migrate them back into a new cluster. The underlying snapshots on your cloud provider will only get deleted if you `kubectl delete` the corresponding VolumeSnapshot.

You could also try [velero](https://github.com/vmware-tanzu/velero) as a more heavy-weight Disaster Recovery solution
