### ISSUE TITLE
Option to automatically scale up/down during backup/restore

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/gemini#32]
Some workloads need to be scaled down before a snapshot can be safely created. For gemini to be usable in this case, it will need to automatically scale down the workload before creating a VolumeSnapshot, then scale it back up once the snapshot is done.

In addition, it would be nice to be able to automatically scale workloads down and back up when a restore is requested.

For more details, see the [conversation in the community slack](https://fairwindscommunity.slack.com/archives/C01957ALM9S/p1606131149001100)

**Comment by grimmy** [comment]
It would be awesome if we could also attach a side car pre-snapshot and detach it post-snapshot.  The use case here is to hold a transactional lock in a database.

**Comment by rbren** [comment]
Not stale - WIP

**Comment by darren-rose** [comment]
do we know when this will be released?

**Comment by rbren** [comment]
Hey Darren - this is currently stuck on some k8s API issues. Still trying to debug.
