### ISSUE TITLE
Add rate-limit to snapshots

### ISSUE THREAD

**Issue by liorfranko** [FairwindsOps/gemini#44]
We're taking ~15 snapshots, and we've reached Amazon's ConcurrentSnapshotLimitExceeded.
From what I see, every 1 hour all the snapshots are created in parallel.
Can you add a mechanism to control how many snapshots are created in parallel?

**Comment by rbren** [comment]
That's a great request - we've seen the same on DigitalOcean.

Not sure when we'll have time to implement, but happy to accept a PR here!

**Comment by DavidSpek** [comment]
I believe the code needed to track this will also be useful for the Prometheus metric I suggested in https://github.com/FairwindsOps/gemini/issues/43#issuecomment-896347138
