### ISSUE TITLE
feat: restore a PVC from the latest backup when empty

### ISSUE THREAD

**Issue by Morriz** [FairwindsOps/gemini#47]
Hi, your solution seems like a dream because it takes care of a lot of headaches. One thing that could be very useful is a routine that checks if the source PVC is empty, and let the controller start a restore procedure from the latest restore point.
This would result in transparent PVC restore upon cluster restoration (by re-applying only manifests).

Does this feature already exist or would that be easy to implement?

**Comment by rbren** [comment]
Thanks for the kind words!

I'm not sure I fully understand the use-case here. Maybe some example manifests or workflows would help?

**Comment by Morriz** [comment]
IF:
- after all manifests have been backed up by a backup solution (excluding PVCs)
- and after then destroying a cluster and bringing it back up
- redeploying all the manifests (including gemini CRs)
THEN:
The controller receives the CRs and upon processing them can check the PVC if it is empty, and could start a routine to restore onto that empty PVC from the latest snapshot

Hope that is clear enough ;)

**Comment by Morriz** [comment]
point I am making is to allow devs to specify snapshotting strategy, but allow platform admins to schedule cluster backups...in the scenario I just gave this would work together just fine :)
