### ISSUE TITLE
Change documentation to say "snapshot" rather than "backup"

### ISSUE THREAD

**Issue by tuxpeople** [FairwindsOps/gemini#49]
Hi

As those two terms are both used here, mixed up, I wanted to ask for a clarification: Does Gemini make backups, or snapshots? My understanding is that it's a Snapshot managing tool not a backup tool. Am I right?

Br
Thomas

**Comment by sudermanjr** [comment]
@tuxpeople thanks for asking! Gemini is definitely a snapshot management tool.

**Comment by tuxpeople** [comment]
Thanks!
